### ISSUE TITLE
[BUG] Grayskull doesn't clean temporary directories

### ISSUE THREAD

**Issue by spinoch** [conda-incubator/grayskull#214] opened 2021-03-04 14:30 UTC
**Describe the bug**
My `/tmp` partition becomes filled after running `grayskull pypi ...` a couple of times

**To Reproduce**
1. Run `grayskull pypi ...`
2. Observe that there are `/tmp/grayskull-*` directories which have not been removed after the command has finished

**Expected behavior**
grayskull automatically removes temporary directories after usage

**Environment:**
grayskull --version
0.8.5

**Comment by ocefpaf** [comment] 2021-03-04 17:29
Should it? As far as I know it is up to the distro to set up a cleaning routine for the /tmp directory.

For example: https://askubuntu.com/questions/20783/how-is-the-tmp-directory-cleaned-up

**Comment by marcelotrevisani** [comment] 2021-03-04 17:43
Hi @spinoch , thanks for taking the time to report it. But as @ocefpaf mentioned that is not really a bug, as the temporary folders are managed by the OS and are cleaned periodically.

If you want to, we are open to improvements, and I suggest maybe create an option called ``--clean-tmp`` and it will clean the temporary folders which ``grayskull`` created after it finishes. That should not be difficult to implement, we are very open to new contributors if you want to try it :)

**Comment by marcelotrevisani** [comment] 2021-03-04 19:04
I will close this as was explained that it is not a bug. Thanks for your time reporting it.

**Closed by marcelotrevisani** 2021-03-04 19:04 UTC
Labels: bug

**Comment by spinoch** [comment] 2021-03-04 20:32
Ah, I thought this was standard practice in software engineering.

> That should not be difficult to implement, we are very open to new contributors if you want to try it :)

I would like to, but time constraints... Perhaps on my next batch of creating conda-forge recipes ;)
