### ISSUE TITLE
[FEATURE] Handling extras

### ISSUE THREAD

**Issue by cyprienc** [conda-incubator/grayskull#229] opened 2021-06-16 07:30 UTC
Hi,

Would it please be possible to handle extras (like in `pip install pettingzoo[atari]`) when generating the recipe?

Ideally, doing `grayskull pypi pettingzoo[atari]` would fetch the extras and add them to the recipe.

Thanks,

Cyprien

**Comment by marcelotrevisani** [comment] 2021-06-16 09:01
hi @cyprienc ,

That is an interesting idea.
It is not currently supported in grayskull, but it is a nice feature to have, indeed.
I will add it to my todos :)

**Comment by zzhengnan** [comment] 2021-08-06 11:46
@marcelotrevisani Thanks for this awesome tool, first and foremost! Are you open to outside contributions? If so and if this feature isn't something you are actively working on, I'd love to help out.

**Comment by marcelotrevisani** [comment] 2021-08-08 20:58
> @marcelotrevisani Thanks for this awesome tool, first and foremost! Are you open to outside contributions? If so and if this feature isn't something you are actively working on, I'd love to help out.

Hi @zzhengnan , sorry for my delay. Yes, please. We would love some help, contributions are very welcome! :)

**Comment by marcelotrevisani** [comment] 2021-11-03 20:10
Indeed, that can be achievable as you mentioned, we need to parse the CLI add new arguments to pass which extras we wanto to extract and after, as you mentioned, do some logic to add those packages.

are you willing to open a PR?

**Comment by zzhengnan** [comment] 2021-11-13 17:10
I'll likely have limited bandwidth in the next few months. If that's not going to be problematic, I'm happy to keep digging. On the other hand, I want to be respectful of everyone's time and don't want to be the bottleneck for this feature not being built. Please let me know either way.

**Comment by woutdenolf** [comment] 2022-06-18 17:59
Duplicate of https://github.com/conda-incubator/grayskull/issues/150

**Closed** 2022-08-22 13:25 UTC
Labels: enhancement, feature
